apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akka-backend
  template:
    metadata:
      labels:
        app: akka-backend
    spec:
      containers:
      - name: akka-backend
        image: <your_docker_registry>/akka-backend:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: akka-backend
spec:
  selector:
    app: akka-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
