apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-fastapi
  template:
    metadata:
      labels:
        app: backend-fastapi
    spec:
      containers:
      - name: backend-fastapi
        image: <your_docker_registry>/backend-fastapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database-url
