apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: <base64_encoded_username>
  postgres-password: <base64_encoded_password>
  database-url: <base64_encoded_database_url>
